* Short description
  This files describes the progress on PhD thesis of Emilio Depero. It was created on <2020-01-13 Mon>.
* Instructions
  To create the pdf, simply type in the command line:

  *make*

  To view the file type:

  *make view*

  *NOTE:* The Makefile uses latexmk to compile the .tex file and evince to visualize it. Be sure 
  to install these two programs before using the respective comand. Alternatively, The main file PhDthesis.tex
  in the folder *thesis/* can be compiled using any program of choice.
* Structure
** Declaration of Authorship
** Abstract
   - [[./thesis/chapters/abstract.tex]]
** Acknowledgements
   - [[./thesis/chapters/acknowledgements.tex]]
** Preface
   - [[./thesis/chapters/preface.tex]]
** Chapter 1, Introduction
   - [[./thesis/chapters/chapter1/chapter1.tex]]
** Chapter 2, The NA64 experiment
   - [[./thesis/chapters/chapter2/chapter2.tex]]
** Chapter 3, Data Analysis
   - [[./thesis/chapters/chapter3/chapter3.tex]]
** Chapter 4, Results
   - [[./thesis/chapters/chapter4/chapter4.tex]]
** Chapter 5, Future prospects
   - [[./thesis/chapters/chapter5/chapter5.tex]]
** Chapter 6, Conclusion
   - [[./thesis/chapters/chapter6/chapter6.tex]]
** Appendices
*** AppendixA, Dark matter formulas and calculations
   - [[./thesis/chapters/appendices/appendixA.tex]]
*** AppendixB, Physics tool
   - [[./thesis/chapters/appendices/appendixB.tex]]
*** AppendixC, Geant4 simulation
   - [[./thesis/chapters/appendices/appendixC.tex]]
*** AppendixD, Algorithms and particle tracking
   - [[./thesis/chapters/appendices/appendixD.tex]]
*** AppendixE, Statistics
   - [[./thesis/chapters/appendices/appendixE.tex]]
*** AppendixF, Tables
   - [[./thesis/appendices/appendixF.tex]]
* Bibliography
  - [[./thesis/utility/bibliography.bib]]
* Code repository
** Simulation
   All relevant code for the simulation can be found in https://gitlab.cern.ch/P348/na64-tools
   Relevant branches are:
   - [[https://gitlab.cern.ch/P348/na64-tools/-/tree/eth-visiblemode-2021][eth-visiblemode-2021]] used for feasibility studies for 2021 visible mode setup
   - [[https://gitlab.cern.ch/P348/na64-tools/-/tree/eth-semivisible][eth-semivisible]] all relevant code for the semivisible mode analysis developed together with *Cesare Cazzaniga*
   - [[https://gitlab.cern.ch/P348/na64-tools/-/tree/eth-muonmode-2021][eth-muonmode-2021]] used for feasbility studies for the muon setup, developed mostly by *Laura Molina Bueno* and *Henri Sieber*
** Reconstruction 
   The relevant software to reconstruct the data in the standard NA64 format can be found here: https://gitlab.cern.ch/P348/p348-daq
   Relevant branches to this project includes:
   - [[https://gitlab.cern.ch/P348/p348-daq/-/tree/eth-reco][eth-reco]] to reconstruct the data for visible/invisible mode
   - [[https://gitlab.cern.ch/P348/p348-daq/-/tree/eth-reco-muonmode][eth-reco-muonmode]] to reconstruct data for the muon mode to be used in 2021, mostly used for feasibility studies
   - [[https://gitlab.cern.ch/P348/p348-daq/-/tree/eth-reco-semivisible][eth-reco-semivisible]] create for *Cesare Cazzaniga* to save all reconstruction code for the semivisible mode. Used mostly for feasibility studies
   - [[https://gitlab.cern.ch/P348/p348-daq/-/tree/eth-straw][eth-straw]] Create for *Peter Degen* to reconstruct straw hits.
** Analysis
   Tools used for the analysis on the reconstructed data can be found in my own ETH repository at https://gitlab.ethz.ch/na64/na64analysis
** Simulation of Micromegas output
   A dedicated repository was written by me to simulate Micromegas response for different assumption and multiplex mapping.
   The idea behind this deposit is to use the input of NA64 data to simulate the response as reliably as poissible, including noise an extreme topologies, but
   it also supports clustering created by simple physical models. It can be found here: https://gitlab.ethz.ch/na64/mm-clustering
** Plotting the exclusion plot
   data and code for the exclusion plot mostly used some gnu plot provided in the form of some text file.
   The git repository with the relevant information can be retrieved here: [[https://gitlab.cern.ch/P348/NA64-exclusion-plot]]
   To compute the exclusion limit in the full frequentist approach a sample can be found here: https://gitlab.cern.ch/P348/na64limits
* NOTES
  A collection of all notes produced for NA64 can be found [[https://gitlab.cern.ch/P348/na64-papers][here]] with the complete latex. A webpage containing all notes build in a pdf format can be found [[https://gitlab.cern.ch/P348/na64-papers/-/jobs/9911057/artifacts/browse][here]]. A twiki with all information about runs, detector, and computing infrastructure can be found [[https://twiki.cern.ch/twiki/bin/viewauth/P348/WebHome][here]].
* DATA
  What follows is a description for their thesis and their last known location
** NA64 data
   A complete collection of all data collected by NA64 is stored in the [[https://information-technology.web.cern.ch/services/eos-service][eos system]] provided by CERN. They are saved in the directory /eos/experiment/na64/data/cdr . The name of the file follow the format:
   
   - cdr01<batch-number>-<run-number>.dat
     - <batch-number> is the part of the run in chronological order (each file is always mantained at 1.1 GB maximum for optimization purposes) and is always four number, where the first number are filled with 0 if not used.
     - <run-number> is the run number of the file and is always expressed by 6 number, 0 are filled at the beginning if not used by the run number.
** NA64 simulation
   Most simulation performed during myu thesis can be found either on lxplus in /eos/experiment/na64/Tree/ or in essos1@ethz.ch in the folder /mnt/storage/deperoe.
** NA64 clustering
   Some toy data used for Micromegas can be found on essos1@ethz.ch in the folder /mnt/raid/groups/mm-clustering.
** NA64 documents
   A list of useful documents can be found in [[https://cds.cern.ch/collection/NA64][this website]] hosted by CERN 
* External softwares
** Geant4
   For particle simulation
   - can be found here https://geant4.web.cern.ch/
** ROOT
   For data analysis
   - Can be found here https://root.cern.ch/
     + Minuit for fitting https://root.cern.ch/doc/master/Minuit2Page.html
     + RooStat for statistical analysis https://twiki.cern.ch/twiki/bin/view/RooStats/WebHome
** Garfield++
   To simulate reliably interactions and charge spread in gas detector
   - can be found here: https://garfieldpp.web.cern.ch/garfieldpp/
** Genfit
   - For tracking procedures using Kalman filter
     + Can be found https://github.com/GenFit/GenFit
     + Suggested by *Balint Radics*
** Histfitter
   - A useful tools for histogram fitting of complicate models
     + can be found [[https://twiki.cern.ch/twiki/bin/view/Main/HistFitterTutorialOutsideAtlas][here]]
     + Suggested by Mikhail in <2020-04-23 Thu>
     + Still not tested
** Web tool digitizer
   - Useful tool to extract data points from any kind of plot
     * can be found [[https://apps.automeris.io/wpd/][here]]
     * Useful, free and has a desktop version for all OS
     * extremely intuitive
