void invariant-mass-reco-allcuts()
{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Mon May 18 18:23:41 2020) by ROOT version 6.16/00
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",2328,111,1333,843);
   Canvas_1->Range(13.375,-26.20251,19.625,235.8226);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1F *dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1 = new TH1F("dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1","Invariant mass reconstructed with assumed vertex information and reconstructed momentumInvariantMass",3000,0,300);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(151,9);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(152,16);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(153,14);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(154,12);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(155,18);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(156,9);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(157,25);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(158,21);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(159,30);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(160,40);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(161,78);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(162,69);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(163,117);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(164,141);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(165,133);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(166,155);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(167,186);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(168,167);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(169,129);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(170,127);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(171,94);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(172,66);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(173,27);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(174,32);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(175,23);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(176,15);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(177,17);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(178,8);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(179,7);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(180,7);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(181,9);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(182,2);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(183,2);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetBinContent(184,2);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetEntries(1807);
   
   TF1 *doublegaus1 = new TF1("doublegaus","[0]*TMath::Gaus(x, [1], [2]) + [3]*TMath::Gaus(x, [1], [4])",0,300, TF1::EAddToList::kNo);
   doublegaus1->SetFillColor(19);
   doublegaus1->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   doublegaus1->SetLineColor(ci);
   doublegaus1->SetLineWidth(3);
   doublegaus1->SetChisquare(58.4475);
   doublegaus1->SetNDF(29);
   doublegaus1->GetXaxis()->SetLabelFont(42);
   doublegaus1->GetXaxis()->SetLabelSize(0.035);
   doublegaus1->GetXaxis()->SetTitleSize(0.035);
   doublegaus1->GetXaxis()->SetTitleOffset(1);
   doublegaus1->GetXaxis()->SetTitleFont(42);
   doublegaus1->GetYaxis()->SetLabelFont(42);
   doublegaus1->GetYaxis()->SetLabelSize(0.035);
   doublegaus1->GetYaxis()->SetTitleSize(0.035);
   doublegaus1->GetYaxis()->SetTitleFont(42);
   doublegaus1->SetParameter(0,140.6811);
   doublegaus1->SetParError(0,8.827122);
   doublegaus1->SetParLimits(0,0,0);
   doublegaus1->SetParameter(1,16.59735);
   doublegaus1->SetParError(1,0.01112199);
   doublegaus1->SetParLimits(1,0,0);
   doublegaus1->SetParameter(2,0.3321475);
   doublegaus1->SetParError(2,0.01794908);
   doublegaus1->SetParLimits(2,0,0.5161399);
   doublegaus1->SetParameter(3,30.14308);
   doublegaus1->SetParError(3,7.85262);
   doublegaus1->SetParLimits(3,0,0);
   doublegaus1->SetParameter(4,0.7898454);
   doublegaus1->SetParError(4,0.07402378);
   doublegaus1->SetParLimits(4,0.5161399,8.258238);
   doublegaus1->SetParent(dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetListOfFunctions()->Add(doublegaus1);
   
   TPaveStats *ptstats = new TPaveStats(0.6394422,0.3448276,0.8997344,0.9001189,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Mean  =  16.58");
   ptstats_LaTex = ptstats->AddText("Std Dev   = 0.5169");
   ptstats_LaTex = ptstats->AddText("#chi^{2} / ndf = 58.45 / 29");
   ptstats_LaTex = ptstats->AddText("Normcenter = 140.7 #pm 8.8 ");
   ptstats_LaTex = ptstats->AddText("Reconstructed Mass =  16.6 #pm 0.0 ");
   ptstats_LaTex = ptstats->AddText("SigmaCenter = 0.3321 #pm 0.0179 ");
   ptstats_LaTex = ptstats->AddText("NormWide = 30.14 #pm 7.85 ");
   ptstats_LaTex = ptstats->AddText("SigmaWide = 0.7898 #pm 0.0740 ");
   ptstats->SetOptStat(1100);
   ptstats->SetOptFit(111);
   ptstats->Draw();
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1);

   ci = TColor::GetColor("#000099");
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetLineColor(ci);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetLineWidth(3);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetMarkerColor(2);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->SetMarkerStyle(20);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetTitle("Reconstructed Invariant mass [MeV]");
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetRange(141,190);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetLabelFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetLabelSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetTitleSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetTitleOffset(1);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetXaxis()->SetTitleFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetYaxis()->SetTitle("Frequency [a.u.]");
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetYaxis()->SetLabelFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetYaxis()->SetLabelSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetYaxis()->SetTitleSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetYaxis()->SetTitleFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetZaxis()->SetLabelFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetZaxis()->SetLabelSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetZaxis()->SetTitleSize(0.035);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetZaxis()->SetTitleOffset(1);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->GetZaxis()->SetTitleFont(42);
   dmmIXbosmIv3mIrvacuummI13fielddOd_VisibleSetup2021InvariantMass_vertex_convdIInvariantMass_vertex_convInvariantMass_sig_DoubleGaussFit__1->Draw("E");
   
   TPaveText *pt = new TPaveText(0.15,0.94,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   pt->Draw();
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
